[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

[[services]]
name = "journowl-web"

[services.source]
repo = "craftyguru/journowl"
branch = "main"

[services.variables]
NODE_ENV = "production"

[services.domains]
production = "journowl.railway.app"